export const sizeList = [
  { id: 1, name: "Trousers", sizes: [36, 38, 40, 42, 44, 46, 48] },
  { id: 2, name: "Clothes", sizes: ["S", "M", "L", "XL", "XXL", "XXXL"] },
  { id: 3, name: "Shoes", sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44] },
  { id: 4, name: "Jackets", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 5, name: "Shirts", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 6, name: "Sweaters", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 7, name: "Hats", sizes: ["S", "M", "L", "XL"] },
  { id: 8, name: "Gloves", sizes: ["S", "M", "L", "XL"] },
  { id: 9, name: "Bags", sizes: ["Small", "Medium", "Large"] },
  { id: 10, name: "Belts", sizes: ["S", "M", "L", "XL"] },
  { id: 11, name: "Suits", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 12, name: "Underwear", sizes: ["S", "M", "L", "XL"] },
  { id: 13, name: "Socks", sizes: ["S", "M", "L", "XL"] },
  { id: 14, name: "Sportswear", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 15, name: "Swimwear", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 16, name: "Coats", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 17, name: "Shorts", sizes: [36, 38, 40, 42, 44] },
  { id: 18, name: "Hoodies", sizes: ["S", "M", "L", "XL", "XXL"] },
  { id: 19, name: "Rings", sizes: ["Small", "Medium", "Large"] },
  { id: 20, name: "Watches", sizes: ["Small", "Medium", "Large"] },
  { id: 21, name: "T-shirts", sizes: ["S", "M", "L", "XL", "XXL"] },
];
